// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"dockzilla/pkg/domain"
	"encoding/json"

	mock "github.com/stretchr/testify/mock"
)

// NewMockHandler creates a new instance of MockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandler {
	mock := &MockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHandler is an autogenerated mock type for the Handler type
type MockHandler struct {
	mock.Mock
}

type MockHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHandler) EXPECT() *MockHandler_Expecter {
	return &MockHandler_Expecter{mock: &_m.Mock}
}

// Latest provides a mock function for the type MockHandler
func (_mock *MockHandler) Latest(ctx context.Context, kind domain.Kind) (domain.Schema, error) {
	ret := _mock.Called(ctx, kind)

	if len(ret) == 0 {
		panic("no return value specified for Latest")
	}

	var r0 domain.Schema
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Kind) (domain.Schema, error)); ok {
		return returnFunc(ctx, kind)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Kind) domain.Schema); ok {
		r0 = returnFunc(ctx, kind)
	} else {
		r0 = ret.Get(0).(domain.Schema)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Kind) error); ok {
		r1 = returnFunc(ctx, kind)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHandler_Latest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Latest'
type MockHandler_Latest_Call struct {
	*mock.Call
}

// Latest is a helper method to define mock.On call
//   - ctx context.Context
//   - kind domain.Kind
func (_e *MockHandler_Expecter) Latest(ctx any, kind any) *MockHandler_Latest_Call {
	return &MockHandler_Latest_Call{Call: _e.mock.On("Latest", ctx, kind)}
}

func (_c *MockHandler_Latest_Call) Run(run func(ctx context.Context, kind domain.Kind)) *MockHandler_Latest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Kind
		if args[1] != nil {
			arg1 = args[1].(domain.Kind)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_Latest_Call) Return(schema domain.Schema, err error) *MockHandler_Latest_Call {
	_c.Call.Return(schema, err)
	return _c
}

func (_c *MockHandler_Latest_Call) RunAndReturn(run func(ctx context.Context, kind domain.Kind) (domain.Schema, error)) *MockHandler_Latest_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockHandler
func (_mock *MockHandler) List(ctx context.Context, kind domain.Kind) ([]domain.Schema, error) {
	ret := _mock.Called(ctx, kind)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Schema
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Kind) ([]domain.Schema, error)); ok {
		return returnFunc(ctx, kind)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Kind) []domain.Schema); ok {
		r0 = returnFunc(ctx, kind)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Schema)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Kind) error); ok {
		r1 = returnFunc(ctx, kind)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHandler_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockHandler_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - kind domain.Kind
func (_e *MockHandler_Expecter) List(ctx any, kind any) *MockHandler_List_Call {
	return &MockHandler_List_Call{Call: _e.mock.On("List", ctx, kind)}
}

func (_c *MockHandler_List_Call) Run(run func(ctx context.Context, kind domain.Kind)) *MockHandler_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Kind
		if args[1] != nil {
			arg1 = args[1].(domain.Kind)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_List_Call) Return(schemas []domain.Schema, err error) *MockHandler_List_Call {
	_c.Call.Return(schemas, err)
	return _c
}

func (_c *MockHandler_List_Call) RunAndReturn(run func(ctx context.Context, kind domain.Kind) ([]domain.Schema, error)) *MockHandler_List_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockHandler
func (_mock *MockHandler) Register(ctx context.Context, ref domain.SchemaRef, document json.RawMessage) (domain.Schema, error) {
	ret := _mock.Called(ctx, ref, document)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 domain.Schema
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SchemaRef, json.RawMessage) (domain.Schema, error)); ok {
		return returnFunc(ctx, ref, document)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SchemaRef, json.RawMessage) domain.Schema); ok {
		r0 = returnFunc(ctx, ref, document)
	} else {
		r0 = ret.Get(0).(domain.Schema)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.SchemaRef, json.RawMessage) error); ok {
		r1 = returnFunc(ctx, ref, document)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHandler_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockHandler_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - ref domain.SchemaRef
//   - document json.RawMessage
func (_e *MockHandler_Expecter) Register(ctx any, ref any, document any) *MockHandler_Register_Call {
	return &MockHandler_Register_Call{Call: _e.mock.On("Register", ctx, ref, document)}
}

func (_c *MockHandler_Register_Call) Run(run func(ctx context.Context, ref domain.SchemaRef, document json.RawMessage)) *MockHandler_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.SchemaRef
		if args[1] != nil {
			arg1 = args[1].(domain.SchemaRef)
		}
		var arg2 json.RawMessage
		if args[2] != nil {
			arg2 = args[2].(json.RawMessage)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockHandler_Register_Call) Return(schema domain.Schema, err error) *MockHandler_Register_Call {
	_c.Call.Return(schema, err)
	return _c
}

func (_c *MockHandler_Register_Call) RunAndReturn(run func(ctx context.Context, ref domain.SchemaRef, document json.RawMessage) (domain.Schema, error)) *MockHandler_Register_Call {
	_c.Call.Return(run)
	return _c
}

// Retrieve provides a mock function for the type MockHandler
func (_mock *MockHandler) Retrieve(ctx context.Context, ref domain.SchemaRef) (domain.Schema, error) {
	ret := _mock.Called(ctx, ref)

	if len(ret) == 0 {
		panic("no return value specified for Retrieve")
	}

	var r0 domain.Schema
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SchemaRef) (domain.Schema, error)); ok {
		return returnFunc(ctx, ref)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SchemaRef) domain.Schema); ok {
		r0 = returnFunc(ctx, ref)
	} else {
		r0 = ret.Get(0).(domain.Schema)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.SchemaRef) error); ok {
		r1 = returnFunc(ctx, ref)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHandler_Retrieve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Retrieve'
type MockHandler_Retrieve_Call struct {
	*mock.Call
}

// Retrieve is a helper method to define mock.On call
//   - ctx context.Context
//   - ref domain.SchemaRef
func (_e *MockHandler_Expecter) Retrieve(ctx any, ref any) *MockHandler_Retrieve_Call {
	return &MockHandler_Retrieve_Call{Call: _e.mock.On("Retrieve", ctx, ref)}
}

func (_c *MockHandler_Retrieve_Call) Run(run func(ctx context.Context, ref domain.SchemaRef)) *MockHandler_Retrieve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.SchemaRef
		if args[1] != nil {
			arg1 = args[1].(domain.SchemaRef)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_Retrieve_Call) Return(schema domain.Schema, err error) *MockHandler_Retrieve_Call {
	_c.Call.Return(schema, err)
	return _c
}

func (_c *MockHandler_Retrieve_Call) RunAndReturn(run func(ctx context.Context, ref domain.SchemaRef) (domain.Schema, error)) *MockHandler_Retrieve_Call {
	_c.Call.Return(run)
	return _c
}

// Validate provides a mock function for the type MockHandler
func (_mock *MockHandler) Validate(ctx context.Context, ref domain.SchemaRef, payload domain.Payload) error {
	ret := _mock.Called(ctx, ref, payload)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SchemaRef, domain.Payload) error); ok {
		r0 = returnFunc(ctx, ref, payload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHandler_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockHandler_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - ctx context.Context
//   - ref domain.SchemaRef
//   - payload domain.Payload
func (_e *MockHandler_Expecter) Validate(ctx any, ref any, payload any) *MockHandler_Validate_Call {
	return &MockHandler_Validate_Call{Call: _e.mock.On("Validate", ctx, ref, payload)}
}

func (_c *MockHandler_Validate_Call) Run(run func(ctx context.Context, ref domain.SchemaRef, payload domain.Payload)) *MockHandler_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.SchemaRef
		if args[1] != nil {
			arg1 = args[1].(domain.SchemaRef)
		}
		var arg2 domain.Payload
		if args[2] != nil {
			arg2 = args[2].(domain.Payload)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockHandler_Validate_Call) Return(err error) *MockHandler_Validate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHandler_Validate_Call) RunAndReturn(run func(ctx context.Context, ref domain.SchemaRef, payload domain.Payload) error) *MockHandler_Validate_Call {
	_c.Call.Return(run)
	return _c
}
