// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"dockzilla/pkg/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCacheRepository creates a new instance of MockCacheRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCacheRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCacheRepository {
	mock := &MockCacheRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCacheRepository is an autogenerated mock type for the CacheRepository type
type MockCacheRepository struct {
	mock.Mock
}

type MockCacheRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCacheRepository) EXPECT() *MockCacheRepository_Expecter {
	return &MockCacheRepository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockCacheRepository
func (_mock *MockCacheRepository) Get(ctx context.Context, ref domain.SchemaRef) (domain.Schema, error) {
	ret := _mock.Called(ctx, ref)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.Schema
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SchemaRef) (domain.Schema, error)); ok {
		return returnFunc(ctx, ref)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SchemaRef) domain.Schema); ok {
		r0 = returnFunc(ctx, ref)
	} else {
		r0 = ret.Get(0).(domain.Schema)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.SchemaRef) error); ok {
		r1 = returnFunc(ctx, ref)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCacheRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockCacheRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - ref domain.SchemaRef
func (_e *MockCacheRepository_Expecter) Get(ctx any, ref any) *MockCacheRepository_Get_Call {
	return &MockCacheRepository_Get_Call{Call: _e.mock.On("Get", ctx, ref)}
}

func (_c *MockCacheRepository_Get_Call) Run(run func(ctx context.Context, ref domain.SchemaRef)) *MockCacheRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.SchemaRef
		if args[1] != nil {
			arg1 = args[1].(domain.SchemaRef)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCacheRepository_Get_Call) Return(schema domain.Schema, err error) *MockCacheRepository_Get_Call {
	_c.Call.Return(schema, err)
	return _c
}

func (_c *MockCacheRepository_Get_Call) RunAndReturn(run func(ctx context.Context, ref domain.SchemaRef) (domain.Schema, error)) *MockCacheRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function for the type MockCacheRepository
func (_mock *MockCacheRepository) Put(ctx context.Context, schema domain.Schema) error {
	ret := _mock.Called(ctx, schema)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Schema) error); ok {
		r0 = returnFunc(ctx, schema)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCacheRepository_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockCacheRepository_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - schema domain.Schema
func (_e *MockCacheRepository_Expecter) Put(ctx any, schema any) *MockCacheRepository_Put_Call {
	return &MockCacheRepository_Put_Call{Call: _e.mock.On("Put", ctx, schema)}
}

func (_c *MockCacheRepository_Put_Call) Run(run func(ctx context.Context, schema domain.Schema)) *MockCacheRepository_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Schema
		if args[1] != nil {
			arg1 = args[1].(domain.Schema)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCacheRepository_Put_Call) Return(err error) *MockCacheRepository_Put_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCacheRepository_Put_Call) RunAndReturn(run func(ctx context.Context, schema domain.Schema) error) *MockCacheRepository_Put_Call {
	_c.Call.Return(run)
	return _c
}
