// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"dockzilla/pkg/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockRepository
func (_mock *MockRepository) Get(ctx context.Context, ref domain.SchemaRef) (domain.Schema, error) {
	ret := _mock.Called(ctx, ref)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.Schema
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SchemaRef) (domain.Schema, error)); ok {
		return returnFunc(ctx, ref)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SchemaRef) domain.Schema); ok {
		r0 = returnFunc(ctx, ref)
	} else {
		r0 = ret.Get(0).(domain.Schema)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.SchemaRef) error); ok {
		r1 = returnFunc(ctx, ref)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - ref domain.SchemaRef
func (_e *MockRepository_Expecter) Get(ctx any, ref any) *MockRepository_Get_Call {
	return &MockRepository_Get_Call{Call: _e.mock.On("Get", ctx, ref)}
}

func (_c *MockRepository_Get_Call) Run(run func(ctx context.Context, ref domain.SchemaRef)) *MockRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.SchemaRef
		if args[1] != nil {
			arg1 = args[1].(domain.SchemaRef)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Get_Call) Return(schema domain.Schema, err error) *MockRepository_Get_Call {
	_c.Call.Return(schema, err)
	return _c
}

func (_c *MockRepository_Get_Call) RunAndReturn(run func(ctx context.Context, ref domain.SchemaRef) (domain.Schema, error)) *MockRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Latest provides a mock function for the type MockRepository
func (_mock *MockRepository) Latest(ctx context.Context, kind domain.Kind) (domain.Schema, error) {
	ret := _mock.Called(ctx, kind)

	if len(ret) == 0 {
		panic("no return value specified for Latest")
	}

	var r0 domain.Schema
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Kind) (domain.Schema, error)); ok {
		return returnFunc(ctx, kind)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Kind) domain.Schema); ok {
		r0 = returnFunc(ctx, kind)
	} else {
		r0 = ret.Get(0).(domain.Schema)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Kind) error); ok {
		r1 = returnFunc(ctx, kind)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Latest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Latest'
type MockRepository_Latest_Call struct {
	*mock.Call
}

// Latest is a helper method to define mock.On call
//   - ctx context.Context
//   - kind domain.Kind
func (_e *MockRepository_Expecter) Latest(ctx any, kind any) *MockRepository_Latest_Call {
	return &MockRepository_Latest_Call{Call: _e.mock.On("Latest", ctx, kind)}
}

func (_c *MockRepository_Latest_Call) Run(run func(ctx context.Context, kind domain.Kind)) *MockRepository_Latest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Kind
		if args[1] != nil {
			arg1 = args[1].(domain.Kind)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Latest_Call) Return(schema domain.Schema, err error) *MockRepository_Latest_Call {
	_c.Call.Return(schema, err)
	return _c
}

func (_c *MockRepository_Latest_Call) RunAndReturn(run func(ctx context.Context, kind domain.Kind) (domain.Schema, error)) *MockRepository_Latest_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockRepository
func (_mock *MockRepository) List(ctx context.Context, kind domain.Kind) ([]domain.Schema, error) {
	ret := _mock.Called(ctx, kind)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Schema
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Kind) ([]domain.Schema, error)); ok {
		return returnFunc(ctx, kind)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Kind) []domain.Schema); ok {
		r0 = returnFunc(ctx, kind)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Schema)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Kind) error); ok {
		r1 = returnFunc(ctx, kind)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - kind domain.Kind
func (_e *MockRepository_Expecter) List(ctx any, kind any) *MockRepository_List_Call {
	return &MockRepository_List_Call{Call: _e.mock.On("List", ctx, kind)}
}

func (_c *MockRepository_List_Call) Run(run func(ctx context.Context, kind domain.Kind)) *MockRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Kind
		if args[1] != nil {
			arg1 = args[1].(domain.Kind)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_List_Call) Return(schemas []domain.Schema, err error) *MockRepository_List_Call {
	_c.Call.Return(schemas, err)
	return _c
}

func (_c *MockRepository_List_Call) RunAndReturn(run func(ctx context.Context, kind domain.Kind) ([]domain.Schema, error)) *MockRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockRepository
func (_mock *MockRepository) Register(ctx context.Context, schema domain.Schema) (domain.Schema, error) {
	ret := _mock.Called(ctx, schema)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 domain.Schema
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Schema) (domain.Schema, error)); ok {
		return returnFunc(ctx, schema)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Schema) domain.Schema); ok {
		r0 = returnFunc(ctx, schema)
	} else {
		r0 = ret.Get(0).(domain.Schema)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Schema) error); ok {
		r1 = returnFunc(ctx, schema)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockRepository_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - schema domain.Schema
func (_e *MockRepository_Expecter) Register(ctx any, schema any) *MockRepository_Register_Call {
	return &MockRepository_Register_Call{Call: _e.mock.On("Register", ctx, schema)}
}

func (_c *MockRepository_Register_Call) Run(run func(ctx context.Context, schema domain.Schema)) *MockRepository_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Schema
		if args[1] != nil {
			arg1 = args[1].(domain.Schema)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Register_Call) Return(schema1 domain.Schema, err error) *MockRepository_Register_Call {
	_c.Call.Return(schema1, err)
	return _c
}

func (_c *MockRepository_Register_Call) RunAndReturn(run func(ctx context.Context, schema domain.Schema) (domain.Schema, error)) *MockRepository_Register_Call {
	_c.Call.Return(run)
	return _c
}
