package models

import (
	"encoding/json"
	"time"

	"github.com/uptrace/bun"
)

// JobSchemas is a published job payload contract: the JSON Schema a payload of
// a given Kind and version has to satisfy.
//
// Rows are insert-only. Kind and Version together are unique, and the registry
// inserts with ON CONFLICT DO NOTHING, so a version that has been published
// cannot be rewritten under a replica that is already validating against it.
//
// Identifier is left to the column default here rather than generated by the
// domain, because nothing references a schema by identifier: the registry
// addresses rows by (kind, version), which is the reference that travels in a
// job envelope and in the HTTP path.
type JobSchemas struct {
	bun.BaseModel `bun:"table:job_schemas"`

	ID int64 `bun:"id,pk,autoincrement,type:bigint"`
	// The DDL owns the UNIQUE constraint and the default, so the tag carries
	// neither: nullzero plus default make Bun send DEFAULT on insert and read
	// the generated value back.
	Identifier string `bun:"identifier,type:uuid,notnull,nullzero,default:gen_random_uuid()"`

	Kind    string `bun:"kind,notnull"`
	Version string `bun:"version,notnull"`
	// Document is the schema itself, stored and served verbatim.
	Document json.RawMessage `bun:"document,type:jsonb,notnull"`

	CreatedAt time.Time `bun:"created_at,nullzero,notnull,default:now()"`
	UpdatedAt time.Time `bun:"updated_at,nullzero,notnull,default:now()"`
	// ArchivedAt retires a version without deleting it, so a job still on the
	// queue that references it can be explained after the fact.
	ArchivedAt time.Time `bun:"archived_at,nullzero"`
}
