// Package models holds the Bun mappings for the V0 schema defined in
// scripts/sql/00001_init-db.up.sql. The DDL is the source of truth; these
// structs mirror it.
//
// Every table carries two keys, and they are separate things:
//
//   - ID is the database primary key, a bigint the database assigns. It is
//     tagged pk because it is the primary key, and autoincrement because the
//     column is GENERATED ALWAYS AS IDENTITY: Bun leaves it out of the INSERT
//     and reads the assigned value back with RETURNING. It exists for insertion
//     ordering and keyset pagination.
//
//   - Identifier is the domain key. It is generated by the domain before the
//     entity is persisted, so an aggregate can reference its children in memory
//     without waiting on a round trip. Every foreign key in the schema points at
//     it, and it is the only identifier that appears in an API response, a URL
//     or a pagination cursor.
//
// ID must never cross the API boundary. Nothing in the type system enforces
// that, so it is a review rule: exposing it hands out row counts and lets a
// client enumerate.
//
// Because foreign keys reference identifier rather than id, every relation names
// its join explicitly, and repositories look rows up by identifier:
//
//	db.NewSelect().Model(u).Where("identifier = ?", uid)
//
// WherePK targets id, so it is only correct on a model that has already been
// inserted or selected.
//
// Identifiers are plain strings. PostgreSQL parses the canonical form on the
// way in and returns it on the way out, so the driver needs no custom type.
//
// Enumerated columns are PostgreSQL enum types, declared once in the DDL. The
// constants below name those values for Go callers but do not define them: the
// database is the authority, and it rejects anything outside the set. Two
// columns are deliberately not enums, identities.provider and auth_events.kind,
// because their value sets are open.
//
// Tag conventions:
//
//   - nullzero on every nullable column, so a zero Go value is written as NULL
//     rather than as an empty string or the year 0001.
//   - nullzero alongside default:now() on created_at and updated_at, so an
//     unset timestamp falls back to the database default.
//   - rel:belongs-to and rel:has-many always name the join explicitly, because
//     the foreign keys point at identifier rather than at id.
//
// updated_at is maintained by a database trigger, not here. Jobs, the
// reconciler and the health engine all write rows without passing through a
// handler, so application-side timestamping would miss them.
package models

// identities.provider values. An open set: V0 ships only local, and an external
// provider is stored as "oidc:<name>" where the name is chosen by the operator.
// This is why the column is varchar and not an enum type.
const (
	ProviderLocal = "local"
	// ProviderOIDCPrefix prefixes an external OpenID Connect provider.
	ProviderOIDCPrefix = "oidc:"
)

// hosts.connection_type values, enum type host_connection_type.
const (
	ConnectionLocalSocket = "local_socket"
	ConnectionSSH         = "ssh"
)

// hosts.status values, enum type host_status.
const (
	HostStatusUnknown     = "unknown"
	HostStatusReachable   = "reachable"
	HostStatusUnreachable = "unreachable"
)

// apps.desired_state values, enum type app_desired_state.
const (
	DesiredStateRunning = "running"
	DesiredStateStopped = "stopped"
)

// deployments.status values, enum type deployment_status.
const (
	DeploymentQueued     = "queued"
	DeploymentPulling    = "pulling"
	DeploymentStarting   = "starting"
	DeploymentRunning    = "running"
	DeploymentFailed     = "failed"
	DeploymentSuperseded = "superseded"
)

// deployments.triggered_by values, enum type deployment_trigger.
const (
	TriggeredByAPI      = "api"
	TriggeredByCLI      = "cli"
	TriggeredByWebhook  = "webhook"
	TriggeredByRollback = "rollback"
)

// jobs.status values, enum type job_status.
const (
	JobPending   = "pending"
	JobRunning   = "running"
	JobSucceeded = "succeeded"
	JobFailed    = "failed"
)

// auth_events.kind values. An open set that grows with every auditable action,
// which is why the column is varchar and not an enum type.
const (
	AuthEventLoginSuccess   = "login_success"
	AuthEventLoginFailure   = "login_failure"
	AuthEventLogout         = "logout"
	AuthEventSessionRevoked = "session_revoked"
	AuthEventTokenIssued    = "token_issued"
	AuthEventTokenRevoked   = "token_revoked"
	AuthEventAdminCreated   = "admin_created"
	AuthEventClaimConsumed  = "claim_consumed"
)
