// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSchemasHandler creates a new instance of MockSchemasHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSchemasHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSchemasHandler {
	mock := &MockSchemasHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSchemasHandler is an autogenerated mock type for the SchemasHandler type
type MockSchemasHandler struct {
	mock.Mock
}

type MockSchemasHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSchemasHandler) EXPECT() *MockSchemasHandler_Expecter {
	return &MockSchemasHandler_Expecter{mock: &_m.Mock}
}

// List provides a mock function for the type MockSchemasHandler
func (_mock *MockSchemasHandler) List(c *gin.Context) {
	_mock.Called(c)
	return
}

// MockSchemasHandler_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockSchemasHandler_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockSchemasHandler_Expecter) List(c any) *MockSchemasHandler_List_Call {
	return &MockSchemasHandler_List_Call{Call: _e.mock.On("List", c)}
}

func (_c *MockSchemasHandler_List_Call) Run(run func(c *gin.Context)) *MockSchemasHandler_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSchemasHandler_List_Call) Return() *MockSchemasHandler_List_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSchemasHandler_List_Call) RunAndReturn(run func(c *gin.Context)) *MockSchemasHandler_List_Call {
	_c.Run(run)
	return _c
}

// Register provides a mock function for the type MockSchemasHandler
func (_mock *MockSchemasHandler) Register(c *gin.Context) {
	_mock.Called(c)
	return
}

// MockSchemasHandler_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockSchemasHandler_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockSchemasHandler_Expecter) Register(c any) *MockSchemasHandler_Register_Call {
	return &MockSchemasHandler_Register_Call{Call: _e.mock.On("Register", c)}
}

func (_c *MockSchemasHandler_Register_Call) Run(run func(c *gin.Context)) *MockSchemasHandler_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSchemasHandler_Register_Call) Return() *MockSchemasHandler_Register_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSchemasHandler_Register_Call) RunAndReturn(run func(c *gin.Context)) *MockSchemasHandler_Register_Call {
	_c.Run(run)
	return _c
}

// Retrieve provides a mock function for the type MockSchemasHandler
func (_mock *MockSchemasHandler) Retrieve(c *gin.Context) {
	_mock.Called(c)
	return
}

// MockSchemasHandler_Retrieve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Retrieve'
type MockSchemasHandler_Retrieve_Call struct {
	*mock.Call
}

// Retrieve is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockSchemasHandler_Expecter) Retrieve(c any) *MockSchemasHandler_Retrieve_Call {
	return &MockSchemasHandler_Retrieve_Call{Call: _e.mock.On("Retrieve", c)}
}

func (_c *MockSchemasHandler_Retrieve_Call) Run(run func(c *gin.Context)) *MockSchemasHandler_Retrieve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSchemasHandler_Retrieve_Call) Return() *MockSchemasHandler_Retrieve_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSchemasHandler_Retrieve_Call) RunAndReturn(run func(c *gin.Context)) *MockSchemasHandler_Retrieve_Call {
	_c.Run(run)
	return _c
}

// RetrieveLatest provides a mock function for the type MockSchemasHandler
func (_mock *MockSchemasHandler) RetrieveLatest(c *gin.Context) {
	_mock.Called(c)
	return
}

// MockSchemasHandler_RetrieveLatest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrieveLatest'
type MockSchemasHandler_RetrieveLatest_Call struct {
	*mock.Call
}

// RetrieveLatest is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockSchemasHandler_Expecter) RetrieveLatest(c any) *MockSchemasHandler_RetrieveLatest_Call {
	return &MockSchemasHandler_RetrieveLatest_Call{Call: _e.mock.On("RetrieveLatest", c)}
}

func (_c *MockSchemasHandler_RetrieveLatest_Call) Run(run func(c *gin.Context)) *MockSchemasHandler_RetrieveLatest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSchemasHandler_RetrieveLatest_Call) Return() *MockSchemasHandler_RetrieveLatest_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSchemasHandler_RetrieveLatest_Call) RunAndReturn(run func(c *gin.Context)) *MockSchemasHandler_RetrieveLatest_Call {
	_c.Run(run)
	return _c
}
