// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSampleHandler creates a new instance of MockSampleHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSampleHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSampleHandler {
	mock := &MockSampleHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSampleHandler is an autogenerated mock type for the SampleHandler type
type MockSampleHandler struct {
	mock.Mock
}

type MockSampleHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSampleHandler) EXPECT() *MockSampleHandler_Expecter {
	return &MockSampleHandler_Expecter{mock: &_m.Mock}
}

// SayHello provides a mock function for the type MockSampleHandler
func (_mock *MockSampleHandler) SayHello(c *gin.Context) {
	_mock.Called(c)
	return
}

// MockSampleHandler_SayHello_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SayHello'
type MockSampleHandler_SayHello_Call struct {
	*mock.Call
}

// SayHello is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockSampleHandler_Expecter) SayHello(c any) *MockSampleHandler_SayHello_Call {
	return &MockSampleHandler_SayHello_Call{Call: _e.mock.On("SayHello", c)}
}

func (_c *MockSampleHandler_SayHello_Call) Run(run func(c *gin.Context)) *MockSampleHandler_SayHello_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSampleHandler_SayHello_Call) Return() *MockSampleHandler_SayHello_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSampleHandler_SayHello_Call) RunAndReturn(run func(c *gin.Context)) *MockSampleHandler_SayHello_Call {
	_c.Run(run)
	return _c
}

// SendHello provides a mock function for the type MockSampleHandler
func (_mock *MockSampleHandler) SendHello(c *gin.Context) {
	_mock.Called(c)
	return
}

// MockSampleHandler_SendHello_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendHello'
type MockSampleHandler_SendHello_Call struct {
	*mock.Call
}

// SendHello is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockSampleHandler_Expecter) SendHello(c any) *MockSampleHandler_SendHello_Call {
	return &MockSampleHandler_SendHello_Call{Call: _e.mock.On("SendHello", c)}
}

func (_c *MockSampleHandler_SendHello_Call) Run(run func(c *gin.Context)) *MockSampleHandler_SendHello_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSampleHandler_SendHello_Call) Return() *MockSampleHandler_SendHello_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSampleHandler_SendHello_Call) RunAndReturn(run func(c *gin.Context)) *MockSampleHandler_SendHello_Call {
	_c.Run(run)
	return _c
}
