// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDeploymentHandler creates a new instance of MockDeploymentHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeploymentHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeploymentHandler {
	mock := &MockDeploymentHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDeploymentHandler is an autogenerated mock type for the DeploymentHandler type
type MockDeploymentHandler struct {
	mock.Mock
}

type MockDeploymentHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeploymentHandler) EXPECT() *MockDeploymentHandler_Expecter {
	return &MockDeploymentHandler_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockDeploymentHandler
func (_mock *MockDeploymentHandler) Create(c *gin.Context) {
	_mock.Called(c)
	return
}

// MockDeploymentHandler_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockDeploymentHandler_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockDeploymentHandler_Expecter) Create(c any) *MockDeploymentHandler_Create_Call {
	return &MockDeploymentHandler_Create_Call{Call: _e.mock.On("Create", c)}
}

func (_c *MockDeploymentHandler_Create_Call) Run(run func(c *gin.Context)) *MockDeploymentHandler_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDeploymentHandler_Create_Call) Return() *MockDeploymentHandler_Create_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDeploymentHandler_Create_Call) RunAndReturn(run func(c *gin.Context)) *MockDeploymentHandler_Create_Call {
	_c.Run(run)
	return _c
}
