CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  identifier UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
);

CREATE TABLE IF NOT EXISTS identities (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  identifier UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
); 

CREATE TABLE IF NOT EXISTS sessions (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  identifier UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
);

CREATE TABLE IF NOT EXISTS api_tokens (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  identifier UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
);

CREATE TABLE IF NOT EXISTS setup_claims (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  identifier UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
);

CREATE TABLE IF NOT EXISTS auth_events (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  identifier UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
);

---

CREATE TABLE IF NOT EXISTS hosts (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  identifier UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
);

CREATE TABLE IF NOT EXISTS registry_credentials (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  identifier UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
);

CREATE TABLE IF NOT EXISTS apps (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  identifier UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,

);

CREATE TABLE IF NOT EXISTS deployments (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  identifier UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
);

CREATE TABLE IF NOT EXISTS app_env_vars (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  identifier UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
);

CREATE TABLE IF NOT EXISTS app_volumes (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  identifier UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
);

CREATE TABLE IF NOT EXISTS jobs (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  identifier UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
);
