// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"dockzilla/internal/infra/storage/postgres"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTransactor creates a new instance of MockTransactor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactor {
	mock := &MockTransactor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransactor is an autogenerated mock type for the Transactor type
type MockTransactor struct {
	mock.Mock
}

type MockTransactor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactor) EXPECT() *MockTransactor_Expecter {
	return &MockTransactor_Expecter{mock: &_m.Mock}
}

// RunInTx provides a mock function for the type MockTransactor
func (_mock *MockTransactor) RunInTx(ctx context.Context, f postgres.TxFunc) error {
	ret := _mock.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for RunInTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, postgres.TxFunc) error); ok {
		r0 = returnFunc(ctx, f)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactor_RunInTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunInTx'
type MockTransactor_RunInTx_Call struct {
	*mock.Call
}

// RunInTx is a helper method to define mock.On call
//   - ctx context.Context
//   - f postgres.TxFunc
func (_e *MockTransactor_Expecter) RunInTx(ctx any, f any) *MockTransactor_RunInTx_Call {
	return &MockTransactor_RunInTx_Call{Call: _e.mock.On("RunInTx", ctx, f)}
}

func (_c *MockTransactor_RunInTx_Call) Run(run func(ctx context.Context, f postgres.TxFunc)) *MockTransactor_RunInTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 postgres.TxFunc
		if args[1] != nil {
			arg1 = args[1].(postgres.TxFunc)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactor_RunInTx_Call) Return(err error) *MockTransactor_RunInTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactor_RunInTx_Call) RunAndReturn(run func(ctx context.Context, f postgres.TxFunc) error) *MockTransactor_RunInTx_Call {
	_c.Call.Return(run)
	return _c
}
