// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"dockzilla/internal/infra/storage/cache"

	mock "github.com/stretchr/testify/mock"
)

// NewMockOption creates a new instance of MockOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOption {
	mock := &MockOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOption is an autogenerated mock type for the Option type
type MockOption struct {
	mock.Mock
}

type MockOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOption) EXPECT() *MockOption_Expecter {
	return &MockOption_Expecter{mock: &_m.Mock}
}

// apply provides a mock function for the type MockOption
func (_mock *MockOption) apply(s *cache.Storage) {
	_mock.Called(s)
	return
}

// MockOption_apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'apply'
type MockOption_apply_Call struct {
	*mock.Call
}

// apply is a helper method to define mock.On call
//   - s *cache.Storage
func (_e *MockOption_Expecter) apply(s any) *MockOption_apply_Call {
	return &MockOption_apply_Call{Call: _e.mock.On("apply", s)}
}

func (_c *MockOption_apply_Call) Run(run func(s *cache.Storage)) *MockOption_apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *cache.Storage
		if args[0] != nil {
			arg0 = args[0].(*cache.Storage)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOption_apply_Call) Return() *MockOption_apply_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockOption_apply_Call) RunAndReturn(run func(s *cache.Storage)) *MockOption_apply_Call {
	_c.Run(run)
	return _c
}
