// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockHandler creates a new instance of MockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandler {
	mock := &MockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHandler is an autogenerated mock type for the Handler type
type MockHandler struct {
	mock.Mock
}

type MockHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHandler) EXPECT() *MockHandler_Expecter {
	return &MockHandler_Expecter{mock: &_m.Mock}
}

// SayHello provides a mock function for the type MockHandler
func (_mock *MockHandler) SayHello(ctx context.Context, name string) (string, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for SayHello")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHandler_SayHello_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SayHello'
type MockHandler_SayHello_Call struct {
	*mock.Call
}

// SayHello is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockHandler_Expecter) SayHello(ctx any, name any) *MockHandler_SayHello_Call {
	return &MockHandler_SayHello_Call{Call: _e.mock.On("SayHello", ctx, name)}
}

func (_c *MockHandler_SayHello_Call) Run(run func(ctx context.Context, name string)) *MockHandler_SayHello_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_SayHello_Call) Return(s string, err error) *MockHandler_SayHello_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockHandler_SayHello_Call) RunAndReturn(run func(ctx context.Context, name string) (string, error)) *MockHandler_SayHello_Call {
	_c.Call.Return(run)
	return _c
}

// SendHello provides a mock function for the type MockHandler
func (_mock *MockHandler) SendHello(ctx context.Context, name string) error {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for SendHello")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHandler_SendHello_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendHello'
type MockHandler_SendHello_Call struct {
	*mock.Call
}

// SendHello is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockHandler_Expecter) SendHello(ctx any, name any) *MockHandler_SendHello_Call {
	return &MockHandler_SendHello_Call{Call: _e.mock.On("SendHello", ctx, name)}
}

func (_c *MockHandler_SendHello_Call) Run(run func(ctx context.Context, name string)) *MockHandler_SendHello_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_SendHello_Call) Return(err error) *MockHandler_SendHello_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHandler_SendHello_Call) RunAndReturn(run func(ctx context.Context, name string) error) *MockHandler_SendHello_Call {
	_c.Call.Return(run)
	return _c
}
