// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"dockzilla/pkg/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockHandler creates a new instance of MockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandler {
	mock := &MockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHandler is an autogenerated mock type for the Handler type
type MockHandler struct {
	mock.Mock
}

type MockHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHandler) EXPECT() *MockHandler_Expecter {
	return &MockHandler_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockHandler
func (_mock *MockHandler) Create(ctx context.Context, deployment *domain.CreateDeploymentInput) (domain.UUID, error) {
	ret := _mock.Called(ctx, deployment)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.CreateDeploymentInput) (domain.UUID, error)); ok {
		return returnFunc(ctx, deployment)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.CreateDeploymentInput) domain.UUID); ok {
		r0 = returnFunc(ctx, deployment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.CreateDeploymentInput) error); ok {
		r1 = returnFunc(ctx, deployment)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHandler_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockHandler_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - deployment *domain.CreateDeploymentInput
func (_e *MockHandler_Expecter) Create(ctx any, deployment any) *MockHandler_Create_Call {
	return &MockHandler_Create_Call{Call: _e.mock.On("Create", ctx, deployment)}
}

func (_c *MockHandler_Create_Call) Run(run func(ctx context.Context, deployment *domain.CreateDeploymentInput)) *MockHandler_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.CreateDeploymentInput
		if args[1] != nil {
			arg1 = args[1].(*domain.CreateDeploymentInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_Create_Call) Return(uUID domain.UUID, err error) *MockHandler_Create_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockHandler_Create_Call) RunAndReturn(run func(ctx context.Context, deployment *domain.CreateDeploymentInput) (domain.UUID, error)) *MockHandler_Create_Call {
	_c.Call.Return(run)
	return _c
}
