// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"dockzilla/pkg/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Insert provides a mock function for the type MockRepository
func (_mock *MockRepository) Insert(context1 context.Context, deployment domain.Deployment) (domain.UUID, error) {
	ret := _mock.Called(context1, deployment)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 domain.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Deployment) (domain.UUID, error)); ok {
		return returnFunc(context1, deployment)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Deployment) domain.UUID); ok {
		r0 = returnFunc(context1, deployment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Deployment) error); ok {
		r1 = returnFunc(context1, deployment)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - context1 context.Context
//   - deployment domain.Deployment
func (_e *MockRepository_Expecter) Insert(context1 any, deployment any) *MockRepository_Insert_Call {
	return &MockRepository_Insert_Call{Call: _e.mock.On("Insert", context1, deployment)}
}

func (_c *MockRepository_Insert_Call) Run(run func(context1 context.Context, deployment domain.Deployment)) *MockRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Deployment
		if args[1] != nil {
			arg1 = args[1].(domain.Deployment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Insert_Call) Return(uUID domain.UUID, err error) *MockRepository_Insert_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockRepository_Insert_Call) RunAndReturn(run func(context1 context.Context, deployment domain.Deployment) (domain.UUID, error)) *MockRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}
