// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"dockzilla/pkg/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockJobOption creates a new instance of MockJobOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobOption {
	mock := &MockJobOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJobOption is an autogenerated mock type for the JobOption type
type MockJobOption struct {
	mock.Mock
}

type MockJobOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJobOption) EXPECT() *MockJobOption_Expecter {
	return &MockJobOption_Expecter{mock: &_m.Mock}
}

// apply provides a mock function for the type MockJobOption
func (_mock *MockJobOption) apply(c *domain.JobConfig) {
	_mock.Called(c)
	return
}

// MockJobOption_apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'apply'
type MockJobOption_apply_Call struct {
	*mock.Call
}

// apply is a helper method to define mock.On call
//   - c *domain.JobConfig
func (_e *MockJobOption_Expecter) apply(c any) *MockJobOption_apply_Call {
	return &MockJobOption_apply_Call{Call: _e.mock.On("apply", c)}
}

func (_c *MockJobOption_apply_Call) Run(run func(c *domain.JobConfig)) *MockJobOption_apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *domain.JobConfig
		if args[0] != nil {
			arg0 = args[0].(*domain.JobConfig)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockJobOption_apply_Call) Return() *MockJobOption_apply_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockJobOption_apply_Call) RunAndReturn(run func(c *domain.JobConfig)) *MockJobOption_apply_Call {
	_c.Run(run)
	return _c
}
