// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"dockzilla/internal/core/jobs"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUCOption creates a new instance of MockUCOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUCOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUCOption {
	mock := &MockUCOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUCOption is an autogenerated mock type for the UCOption type
type MockUCOption struct {
	mock.Mock
}

type MockUCOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUCOption) EXPECT() *MockUCOption_Expecter {
	return &MockUCOption_Expecter{mock: &_m.Mock}
}

// apply provides a mock function for the type MockUCOption
func (_mock *MockUCOption) apply(u *jobs.UseCase) {
	_mock.Called(u)
	return
}

// MockUCOption_apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'apply'
type MockUCOption_apply_Call struct {
	*mock.Call
}

// apply is a helper method to define mock.On call
//   - u *jobs.UseCase
func (_e *MockUCOption_Expecter) apply(u any) *MockUCOption_apply_Call {
	return &MockUCOption_apply_Call{Call: _e.mock.On("apply", u)}
}

func (_c *MockUCOption_apply_Call) Run(run func(u *jobs.UseCase)) *MockUCOption_apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *jobs.UseCase
		if args[0] != nil {
			arg0 = args[0].(*jobs.UseCase)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUCOption_apply_Call) Return() *MockUCOption_apply_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUCOption_apply_Call) RunAndReturn(run func(u *jobs.UseCase)) *MockUCOption_apply_Call {
	_c.Run(run)
	return _c
}
