// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"dockzilla/internal/core/jobs"

	mock "github.com/stretchr/testify/mock"
)

// NewMockEngineOption creates a new instance of MockEngineOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEngineOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEngineOption {
	mock := &MockEngineOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEngineOption is an autogenerated mock type for the EngineOption type
type MockEngineOption struct {
	mock.Mock
}

type MockEngineOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEngineOption) EXPECT() *MockEngineOption_Expecter {
	return &MockEngineOption_Expecter{mock: &_m.Mock}
}

// apply provides a mock function for the type MockEngineOption
func (_mock *MockEngineOption) apply(e *jobs.Engine) {
	_mock.Called(e)
	return
}

// MockEngineOption_apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'apply'
type MockEngineOption_apply_Call struct {
	*mock.Call
}

// apply is a helper method to define mock.On call
//   - e *jobs.Engine
func (_e *MockEngineOption_Expecter) apply(e any) *MockEngineOption_apply_Call {
	return &MockEngineOption_apply_Call{Call: _e.mock.On("apply", e)}
}

func (_c *MockEngineOption_apply_Call) Run(run func(e *jobs.Engine)) *MockEngineOption_apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *jobs.Engine
		if args[0] != nil {
			arg0 = args[0].(*jobs.Engine)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEngineOption_apply_Call) Return() *MockEngineOption_apply_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEngineOption_apply_Call) RunAndReturn(run func(e *jobs.Engine)) *MockEngineOption_apply_Call {
	_c.Run(run)
	return _c
}
