// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"dockzilla/pkg/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockHandler creates a new instance of MockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandler {
	mock := &MockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHandler is an autogenerated mock type for the Handler type
type MockHandler struct {
	mock.Mock
}

type MockHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHandler) EXPECT() *MockHandler_Expecter {
	return &MockHandler_Expecter{mock: &_m.Mock}
}

// Enqueue provides a mock function for the type MockHandler
func (_mock *MockHandler) Enqueue(ctx context.Context, kind domain.Kind, payload domain.JobsPayload, opts ...domain.JobOption) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, kind, payload, opts)
	} else {
		tmpRet = _mock.Called(ctx, kind, payload)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Enqueue")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Kind, domain.JobsPayload, ...domain.JobOption) error); ok {
		r0 = returnFunc(ctx, kind, payload, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHandler_Enqueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enqueue'
type MockHandler_Enqueue_Call struct {
	*mock.Call
}

// Enqueue is a helper method to define mock.On call
//   - ctx context.Context
//   - kind domain.Kind
//   - payload domain.JobsPayload
//   - opts ...domain.JobOption
func (_e *MockHandler_Expecter) Enqueue(ctx any, kind any, payload any, opts ...any) *MockHandler_Enqueue_Call {
	return &MockHandler_Enqueue_Call{Call: _e.mock.On("Enqueue",
		append([]any{ctx, kind, payload}, opts...)...)}
}

func (_c *MockHandler_Enqueue_Call) Run(run func(ctx context.Context, kind domain.Kind, payload domain.JobsPayload, opts ...domain.JobOption)) *MockHandler_Enqueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Kind
		if args[1] != nil {
			arg1 = args[1].(domain.Kind)
		}
		var arg2 domain.JobsPayload
		if args[2] != nil {
			arg2 = args[2].(domain.JobsPayload)
		}
		var arg3 []domain.JobOption
		var variadicArgs []domain.JobOption
		if len(args) > 3 {
			variadicArgs = args[3].([]domain.JobOption)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockHandler_Enqueue_Call) Return(err error) *MockHandler_Enqueue_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHandler_Enqueue_Call) RunAndReturn(run func(ctx context.Context, kind domain.Kind, payload domain.JobsPayload, opts ...domain.JobOption) error) *MockHandler_Enqueue_Call {
	_c.Call.Return(run)
	return _c
}
