// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"dockzilla/pkg/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Consume provides a mock function for the type MockRepository
func (_mock *MockRepository) Consume(ctx context.Context, dispatch domain.Dispatch) error {
	ret := _mock.Called(ctx, dispatch)

	if len(ret) == 0 {
		panic("no return value specified for Consume")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Dispatch) error); ok {
		r0 = returnFunc(ctx, dispatch)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Consume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Consume'
type MockRepository_Consume_Call struct {
	*mock.Call
}

// Consume is a helper method to define mock.On call
//   - ctx context.Context
//   - dispatch domain.Dispatch
func (_e *MockRepository_Expecter) Consume(ctx any, dispatch any) *MockRepository_Consume_Call {
	return &MockRepository_Consume_Call{Call: _e.mock.On("Consume", ctx, dispatch)}
}

func (_c *MockRepository_Consume_Call) Run(run func(ctx context.Context, dispatch domain.Dispatch)) *MockRepository_Consume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Dispatch
		if args[1] != nil {
			arg1 = args[1].(domain.Dispatch)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Consume_Call) Return(err error) *MockRepository_Consume_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Consume_Call) RunAndReturn(run func(ctx context.Context, dispatch domain.Dispatch) error) *MockRepository_Consume_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockRepository
func (_mock *MockRepository) Insert(ctx context.Context, msg domain.Message, opts ...domain.JobOption) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, msg, opts)
	} else {
		tmpRet = _mock.Called(ctx, msg)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Message, ...domain.JobOption) error); ok {
		r0 = returnFunc(ctx, msg, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - msg domain.Message
//   - opts ...domain.JobOption
func (_e *MockRepository_Expecter) Insert(ctx any, msg any, opts ...any) *MockRepository_Insert_Call {
	return &MockRepository_Insert_Call{Call: _e.mock.On("Insert",
		append([]any{ctx, msg}, opts...)...)}
}

func (_c *MockRepository_Insert_Call) Run(run func(ctx context.Context, msg domain.Message, opts ...domain.JobOption)) *MockRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Message
		if args[1] != nil {
			arg1 = args[1].(domain.Message)
		}
		var arg2 []domain.JobOption
		var variadicArgs []domain.JobOption
		if len(args) > 2 {
			variadicArgs = args[2].([]domain.JobOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockRepository_Insert_Call) Return(err error) *MockRepository_Insert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Insert_Call) RunAndReturn(run func(ctx context.Context, msg domain.Message, opts ...domain.JobOption) error) *MockRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}
