// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"dockzilla/pkg/domain"

	mock "github.com/stretchr/testify/mock"
	"github.com/uptrace/bun"
)

// NewMockQueue creates a new instance of MockQueue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueue(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueue {
	mock := &MockQueue{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQueue is an autogenerated mock type for the Queue type
type MockQueue struct {
	mock.Mock
}

type MockQueue_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueue) EXPECT() *MockQueue_Expecter {
	return &MockQueue_Expecter{mock: &_m.Mock}
}

// Consume provides a mock function for the type MockQueue
func (_mock *MockQueue) Consume(ctx context.Context, handlers map[domain.Kind]func(ctx context.Context, payload []byte, attempt int) error) error {
	ret := _mock.Called(ctx, handlers)

	if len(ret) == 0 {
		panic("no return value specified for Consume")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[domain.Kind]func(ctx context.Context, payload []byte, attempt int) error) error); ok {
		r0 = returnFunc(ctx, handlers)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueue_Consume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Consume'
type MockQueue_Consume_Call struct {
	*mock.Call
}

// Consume is a helper method to define mock.On call
//   - ctx context.Context
//   - handlers map[domain.Kind]func(ctx context.Context, payload []byte, attempt int) error
func (_e *MockQueue_Expecter) Consume(ctx any, handlers any) *MockQueue_Consume_Call {
	return &MockQueue_Consume_Call{Call: _e.mock.On("Consume", ctx, handlers)}
}

func (_c *MockQueue_Consume_Call) Run(run func(ctx context.Context, handlers map[domain.Kind]func(ctx context.Context, payload []byte, attempt int) error)) *MockQueue_Consume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[domain.Kind]func(ctx context.Context, payload []byte, attempt int) error
		if args[1] != nil {
			arg1 = args[1].(map[domain.Kind]func(ctx context.Context, payload []byte, attempt int) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueue_Consume_Call) Return(err error) *MockQueue_Consume_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueue_Consume_Call) RunAndReturn(run func(ctx context.Context, handlers map[domain.Kind]func(ctx context.Context, payload []byte, attempt int) error) error) *MockQueue_Consume_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function for the type MockQueue
func (_mock *MockQueue) Send(ctx context.Context, db bun.IDB, eventType string, payload []byte) error {
	ret := _mock.Called(ctx, db, eventType, payload)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bun.IDB, string, []byte) error); ok {
		r0 = returnFunc(ctx, db, eventType, payload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueue_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockQueue_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - db bun.IDB
//   - eventType string
//   - payload []byte
func (_e *MockQueue_Expecter) Send(ctx any, db any, eventType any, payload any) *MockQueue_Send_Call {
	return &MockQueue_Send_Call{Call: _e.mock.On("Send", ctx, db, eventType, payload)}
}

func (_c *MockQueue_Send_Call) Run(run func(ctx context.Context, db bun.IDB, eventType string, payload []byte)) *MockQueue_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bun.IDB
		if args[1] != nil {
			arg1 = args[1].(bun.IDB)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockQueue_Send_Call) Return(err error) *MockQueue_Send_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueue_Send_Call) RunAndReturn(run func(ctx context.Context, db bun.IDB, eventType string, payload []byte) error) *MockQueue_Send_Call {
	_c.Call.Return(run)
	return _c
}
