// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"dockzilla/internal/infra/storage/postgres/repository"

	mock "github.com/stretchr/testify/mock"
)

// NewMockJobsOption creates a new instance of MockJobsOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobsOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobsOption {
	mock := &MockJobsOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJobsOption is an autogenerated mock type for the JobsOption type
type MockJobsOption struct {
	mock.Mock
}

type MockJobsOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJobsOption) EXPECT() *MockJobsOption_Expecter {
	return &MockJobsOption_Expecter{mock: &_m.Mock}
}

// apply provides a mock function for the type MockJobsOption
func (_mock *MockJobsOption) apply(j *repository.Jobs) {
	_mock.Called(j)
	return
}

// MockJobsOption_apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'apply'
type MockJobsOption_apply_Call struct {
	*mock.Call
}

// apply is a helper method to define mock.On call
//   - j *repository.Jobs
func (_e *MockJobsOption_Expecter) apply(j any) *MockJobsOption_apply_Call {
	return &MockJobsOption_apply_Call{Call: _e.mock.On("apply", j)}
}

func (_c *MockJobsOption_apply_Call) Run(run func(j *repository.Jobs)) *MockJobsOption_apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *repository.Jobs
		if args[0] != nil {
			arg0 = args[0].(*repository.Jobs)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockJobsOption_apply_Call) Return() *MockJobsOption_apply_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockJobsOption_apply_Call) RunAndReturn(run func(j *repository.Jobs)) *MockJobsOption_apply_Call {
	_c.Run(run)
	return _c
}
