[service]
name = "dockzilla-back"
version = "v1"

[storage]
  [storage.database]
    service_name = "dockzilla-postgres"
    url = "postgres://dev:dev_password_123@localhost:5432/database-dev?sslmode=disable"
  [storage.cache]
    service_name = "dockzilla-redis"
    url = "redis://localhost:6379/0"

[http]
service_name = "dockzilla-http-api"
service_version = "v1"

[http.http_server]
port = 8181
read_timeout = "10s"
write_timeout = "10s"

[http.telemetry]
enabled = true
endpoint = "localhost:4317"
insecure = true
